timing-context {
  bpm = 60
  ppq = 960
}

synth-config {
  sound-font-path = "C:\\tools\\fluidsynth\\soundfonts\\soundfont.sf2"
  fluidsynth-path = "C:\\tools\\fluidsynth\\bin\\fluidsynth.exe"
}

midi-output-config {
  loop-midi-port-name = "ScalaToFluid"
}

midi {
  velocity = 100
  volume = 100
  chorus = 0
  reverb = 0
}

paths {
  tracks = "demo-tracks"
  music-file = "music.scala"
  common-file = "common.scala"
}


